[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Redirect all routes to index.html for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API proxy to production backend
[[redirects]]
  from = "/api/*"
  to = "https://tubenix.onrender.com/api/:splat"
  status = 200
  force = true

# CORS headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Production headers for API calls
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://tubenix.netlify.app"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
    Cache-Control = "no-cache"
