[build]
  command = "npm install && npm run build"
  publish = "build"
  functions = "functions"

[dev]
  command = "npm start"
  port = 3000
  publish = "build"
  targetPort = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle CORS for API requests
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
