services:
  - type: web
    name: tubenix
    env: node
    buildCommand: npm run install-server
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
