services:
  - type: web
    name: tubenix-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      # Add other required environment variables here
      # - key: MONGODB_URI
      #   value: your-mongodb-uri
      # - key: JWT_SECRET
      #   value: your-jwt-secret
      # - key: YOUTUBE_API_KEY
      #   value: your-youtube-api-key
